// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterAssessment.Models;

#nullable disable

namespace WaterAssessment.Migrations
{
    [DbContext(typeof(WaterAssessmentContext))]
    [Migration("20260128162539_Add_LocationType_Model")]
    partial class Add_LocationType_Model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WaterAssessment.Models.Area", b =>
                {
                    b.Property<int>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaID"));

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaID");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("WaterAssessment.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentID"));

                    b.Property<int>("CurrentMeterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Echelon")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("PropellerID")
                        .HasColumnType("int");

                    b.Property<int>("Timer")
                        .HasColumnType("int");

                    b.Property<double>("TotalFlow")
                        .HasColumnType("float");

                    b.HasKey("AssessmentID");

                    b.HasIndex("CurrentMeterID");

                    b.HasIndex("LocationID");

                    b.HasIndex("PropellerID");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("WaterAssessment.Models.AssessmentGate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentID")
                        .HasColumnType("int");

                    b.Property<int>("GateNumber")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentID");

                    b.ToTable("AssessmentGates");
                });

            modelBuilder.Entity("WaterAssessment.Models.Assessment_Employee", b =>
                {
                    b.Property<int>("AssessmentID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.HasKey("AssessmentID", "EmployeeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AssessmentEmployees");
                });

            modelBuilder.Entity("WaterAssessment.Models.CurrentMeter", b =>
                {
                    b.Property<int>("CurrentMeterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrentMeterID"));

                    b.Property<string>("CurrentMeterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrentMeterID");

                    b.ToTable("CurrentMeters");
                });

            modelBuilder.Entity("WaterAssessment.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WaterAssessment.Models.FormValue", b =>
                {
                    b.Property<int>("FormValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormValueID"));

                    b.Property<int>("AssessmentID")
                        .HasColumnType("int");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double>("MeasureTime")
                        .HasColumnType("float");

                    b.Property<double?>("Rev02")
                        .HasColumnType("float");

                    b.Property<double?>("Rev06")
                        .HasColumnType("float");

                    b.Property<double?>("Rev08")
                        .HasColumnType("float");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<double>("SectionArea")
                        .HasColumnType("float");

                    b.Property<double>("SectionFlow")
                        .HasColumnType("float");

                    b.Property<double>("SectionWidth")
                        .HasColumnType("float");

                    b.Property<double>("TotalDepth")
                        .HasColumnType("float");

                    b.Property<double?>("Velocity02")
                        .HasColumnType("float");

                    b.Property<double?>("Velocity06")
                        .HasColumnType("float");

                    b.Property<double?>("Velocity08")
                        .HasColumnType("float");

                    b.Property<double>("VerticalMeanVelocity")
                        .HasColumnType("float");

                    b.HasKey("FormValueID");

                    b.HasIndex("AssessmentID");

                    b.ToTable("FormValues");
                });

            modelBuilder.Entity("WaterAssessment.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<int>("AreaID")
                        .HasColumnType("int");

                    b.Property<int>("GateCount")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationTypeID")
                        .HasColumnType("int");

                    b.HasKey("LocationID");

                    b.HasIndex("AreaID");

                    b.HasIndex("LocationTypeID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WaterAssessment.Models.LocationType", b =>
                {
                    b.Property<int>("LocationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationTypeID"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationTypeID");

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            LocationTypeID = 1,
                            Title = "کانال"
                        },
                        new
                        {
                            LocationTypeID = 2,
                            Title = "زهکش"
                        });
                });

            modelBuilder.Entity("WaterAssessment.Models.Propeller", b =>
                {
                    b.Property<int>("PropellerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropellerID"));

                    b.Property<double>("A1")
                        .HasColumnType("float");

                    b.Property<double?>("A2")
                        .HasColumnType("float");

                    b.Property<double?>("A3")
                        .HasColumnType("float");

                    b.Property<double>("B1")
                        .HasColumnType("float");

                    b.Property<double?>("B2")
                        .HasColumnType("float");

                    b.Property<double?>("B3")
                        .HasColumnType("float");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("PropellerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TransitionPoint1")
                        .HasColumnType("float");

                    b.Property<double?>("TransitionPoint2")
                        .HasColumnType("float");

                    b.HasKey("PropellerID");

                    b.ToTable("Propellers");
                });

            modelBuilder.Entity("WaterAssessment.Models.Assessment", b =>
                {
                    b.HasOne("WaterAssessment.Models.CurrentMeter", "CurrentMeter")
                        .WithMany("Assessments")
                        .HasForeignKey("CurrentMeterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterAssessment.Models.Location", "Location")
                        .WithMany("Assessments")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterAssessment.Models.Propeller", "Propeller")
                        .WithMany("Assessments")
                        .HasForeignKey("PropellerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentMeter");

                    b.Navigation("Location");

                    b.Navigation("Propeller");
                });

            modelBuilder.Entity("WaterAssessment.Models.AssessmentGate", b =>
                {
                    b.HasOne("WaterAssessment.Models.Assessment", "Assessment")
                        .WithMany("GateOpenings")
                        .HasForeignKey("AssessmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("WaterAssessment.Models.Assessment_Employee", b =>
                {
                    b.HasOne("WaterAssessment.Models.Assessment", "Assessment")
                        .WithMany("AssessmentEmployees")
                        .HasForeignKey("AssessmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterAssessment.Models.Employee", "Employee")
                        .WithMany("AssessmentEmployees")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WaterAssessment.Models.FormValue", b =>
                {
                    b.HasOne("WaterAssessment.Models.Assessment", "Assessment")
                        .WithMany("FormValues")
                        .HasForeignKey("AssessmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("WaterAssessment.Models.Location", b =>
                {
                    b.HasOne("WaterAssessment.Models.Area", "Area")
                        .WithMany("Locations")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterAssessment.Models.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("WaterAssessment.Models.Area", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("WaterAssessment.Models.Assessment", b =>
                {
                    b.Navigation("AssessmentEmployees");

                    b.Navigation("FormValues");

                    b.Navigation("GateOpenings");
                });

            modelBuilder.Entity("WaterAssessment.Models.CurrentMeter", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("WaterAssessment.Models.Employee", b =>
                {
                    b.Navigation("AssessmentEmployees");
                });

            modelBuilder.Entity("WaterAssessment.Models.Location", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("WaterAssessment.Models.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("WaterAssessment.Models.Propeller", b =>
                {
                    b.Navigation("Assessments");
                });
#pragma warning restore 612, 618
        }
    }
}
